-- 2023-02-16 15:59:25
-- https://school.programmers.co.kr/learn/courses/30/lessons/59415

SELECT MAX(DATETIME) FROM ANIMAL_INS

SELECT DATETIME FROM ANIMAL_INS
ORDER BY DATETIME DESC LIMIT 1

SELECT DATETIME FROM ANIMAL_INS
WHERE DATETIME = 
    (SELECT MAX(DATETIME) AS DATETIME FROM ANIMAL_INS)