-- 2023-02-28 19:08:29
-- https://school.programmers.co.kr/learn/courses/30/lessons/132204

SELECT A.APNT_NO, B.PT_NAME, A.PT_NO, C.MCDP_CD, C.DR_NAME, A.APNT_YMD FROM APPOINTMENT A
JOIN PATIENT B ON A.PT_NO = B.PT_NO
JOIN DOCTOR C ON A.MDDR_ID = C.DR_ID
WHERE DATE(APNT_YMD) LIKE DATE('2022-04-13') 
    AND A.APNT_CNCL_YMD IS NULL
    AND A.APNT_CNCL_YN LIKE 'N'
    AND A.MCDP_CD LIKE 'CS'
ORDER BY A.APNT_YMD