-- 2023-02-24 00:21:25
-- https://school.programmers.co.kr/learn/courses/30/lessons/157339

SELECT A.CAR_ID, A.CAR_TYPE, TRUNCATE(30*A.DAILY_FEE*(1-(C.DISCOUNT_RATE/100)), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단', 'SUV')
    AND C.DURATION_TYPE LIKE '30일%'
    AND A.CAR_ID NOT IN 
        (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
        WHERE B.START_DATE < DATE('2022-12-01') AND B.END_DATE > DATE('2022-11-01')
         ) -- 날짜 선정이 까다로움
    AND TRUNCATE(30*A.DAILY_FEE*(1-(C.DISCOUNT_RATE/100)), 0) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC