-- 2023-02-24 20:19:02
-- https://school.programmers.co.kr/learn/courses/30/lessons/59045

-- 정답 1
SELECT ANIMAL_ID, ANIMAL_TYPE, NAME FROM ANIMAL_INS
WHERE (SEX_UPON_INTAKE LIKE 'Intact%')
AND ANIMAL_ID IN
    (SELECT ANIMAL_ID FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY ANIMAL_ID

-- 정답 2
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE (I.SEX_UPON_INTAKE LIKE 'Intact%')
AND (O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR O.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY I.ANIMAL_ID