-- 2023-02-24 12:55:03
-- https://school.programmers.co.kr/learn/courses/30/lessons/131123

-- 정답
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN 
    (SELECT FOOD_TYPE, MAX(FAVORITES) FROM REST_INFO
    GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC

-- 오답 1
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES FROM REST_INFO
WHERE (REST_ID, FAVORITES) IN 
    (SELECT REST_ID, MAX(FAVORITES) FROM REST_INFO
    GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC

-- 오답 2
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES FROM REST_INFO
WHERE REST_NAME IN (SELECT REST_NAME FROM REST_INFO
    GROUP BY FOOD_TYPE
    ORDER BY FAVORITES DESC)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC

-- 오답 3
SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) AS FAVORITES FROM REST_INFO
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC

-- 오답 1&2: 한 식당에서 양식, 일식 모두 파는 경우가 생김 -> REST_ID나 REST_NAME으로 서브쿼리를 돌리면 X